// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: proto/game.proto

#include "proto/game.pb.h"

#include <algorithm>

#include <google/protobuf/io/coded_stream.h>
#include <google/protobuf/extension_set.h>
#include <google/protobuf/wire_format_lite.h>
#include <google/protobuf/descriptor.h>
#include <google/protobuf/generated_message_reflection.h>
#include <google/protobuf/reflection_ops.h>
#include <google/protobuf/wire_format.h>
// @@protoc_insertion_point(includes)
#include <google/protobuf/port_def.inc>
extern PROTOBUF_INTERNAL_EXPORT_proto_2fgame_2eproto ::PROTOBUF_NAMESPACE_ID::internal::SCCInfo<0> scc_info_ActionBindEntry_proto_2fgame_2eproto;
namespace game {
class ActionBindEntryDefaultTypeInternal {
 public:
  ::PROTOBUF_NAMESPACE_ID::internal::ExplicitlyConstructed<ActionBindEntry> _instance;
} _ActionBindEntry_default_instance_;
class GameParamsDefaultTypeInternal {
 public:
  ::PROTOBUF_NAMESPACE_ID::internal::ExplicitlyConstructed<GameParams> _instance;
} _GameParams_default_instance_;
class DungenParamsDefaultTypeInternal {
 public:
  ::PROTOBUF_NAMESPACE_ID::internal::ExplicitlyConstructed<DungenParams> _instance;
} _DungenParams_default_instance_;
class ActionBindsDefaultTypeInternal {
 public:
  ::PROTOBUF_NAMESPACE_ID::internal::ExplicitlyConstructed<ActionBinds> _instance;
} _ActionBinds_default_instance_;
}  // namespace game
static void InitDefaultsscc_info_ActionBindEntry_proto_2fgame_2eproto() {
  GOOGLE_PROTOBUF_VERIFY_VERSION;

  {
    void* ptr = &::game::_ActionBindEntry_default_instance_;
    new (ptr) ::game::ActionBindEntry();
    ::PROTOBUF_NAMESPACE_ID::internal::OnShutdownDestroyMessage(ptr);
  }
}

::PROTOBUF_NAMESPACE_ID::internal::SCCInfo<0> scc_info_ActionBindEntry_proto_2fgame_2eproto =
    {{ATOMIC_VAR_INIT(::PROTOBUF_NAMESPACE_ID::internal::SCCInfoBase::kUninitialized), 0, 0, InitDefaultsscc_info_ActionBindEntry_proto_2fgame_2eproto}, {}};

static void InitDefaultsscc_info_ActionBinds_proto_2fgame_2eproto() {
  GOOGLE_PROTOBUF_VERIFY_VERSION;

  {
    void* ptr = &::game::_ActionBinds_default_instance_;
    new (ptr) ::game::ActionBinds();
    ::PROTOBUF_NAMESPACE_ID::internal::OnShutdownDestroyMessage(ptr);
  }
}

::PROTOBUF_NAMESPACE_ID::internal::SCCInfo<1> scc_info_ActionBinds_proto_2fgame_2eproto =
    {{ATOMIC_VAR_INIT(::PROTOBUF_NAMESPACE_ID::internal::SCCInfoBase::kUninitialized), 1, 0, InitDefaultsscc_info_ActionBinds_proto_2fgame_2eproto}, {
      &scc_info_ActionBindEntry_proto_2fgame_2eproto.base,}};

static void InitDefaultsscc_info_DungenParams_proto_2fgame_2eproto() {
  GOOGLE_PROTOBUF_VERIFY_VERSION;

  {
    void* ptr = &::game::_DungenParams_default_instance_;
    new (ptr) ::game::DungenParams();
    ::PROTOBUF_NAMESPACE_ID::internal::OnShutdownDestroyMessage(ptr);
  }
}

::PROTOBUF_NAMESPACE_ID::internal::SCCInfo<0> scc_info_DungenParams_proto_2fgame_2eproto =
    {{ATOMIC_VAR_INIT(::PROTOBUF_NAMESPACE_ID::internal::SCCInfoBase::kUninitialized), 0, 0, InitDefaultsscc_info_DungenParams_proto_2fgame_2eproto}, {}};

static void InitDefaultsscc_info_GameParams_proto_2fgame_2eproto() {
  GOOGLE_PROTOBUF_VERIFY_VERSION;

  {
    void* ptr = &::game::_GameParams_default_instance_;
    new (ptr) ::game::GameParams();
    ::PROTOBUF_NAMESPACE_ID::internal::OnShutdownDestroyMessage(ptr);
  }
}

::PROTOBUF_NAMESPACE_ID::internal::SCCInfo<0> scc_info_GameParams_proto_2fgame_2eproto =
    {{ATOMIC_VAR_INIT(::PROTOBUF_NAMESPACE_ID::internal::SCCInfoBase::kUninitialized), 0, 0, InitDefaultsscc_info_GameParams_proto_2fgame_2eproto}, {}};

static ::PROTOBUF_NAMESPACE_ID::Metadata file_level_metadata_proto_2fgame_2eproto[4];
static const ::PROTOBUF_NAMESPACE_ID::EnumDescriptor* file_level_enum_descriptors_proto_2fgame_2eproto[2];
static constexpr ::PROTOBUF_NAMESPACE_ID::ServiceDescriptor const** file_level_service_descriptors_proto_2fgame_2eproto = nullptr;

const ::PROTOBUF_NAMESPACE_ID::uint32 TableStruct_proto_2fgame_2eproto::offsets[] PROTOBUF_SECTION_VARIABLE(protodesc_cold) = {
  ~0u,  // no _has_bits_
  PROTOBUF_FIELD_OFFSET(::game::ActionBindEntry, _internal_metadata_),
  ~0u,  // no _extensions_
  ~0u,  // no _oneof_case_
  ~0u,  // no _weak_field_map_
  PROTOBUF_FIELD_OFFSET(::game::ActionBindEntry, action_),
  PROTOBUF_FIELD_OFFSET(::game::ActionBindEntry, bind_),
  ~0u,  // no _has_bits_
  PROTOBUF_FIELD_OFFSET(::game::GameParams, _internal_metadata_),
  ~0u,  // no _extensions_
  ~0u,  // no _oneof_case_
  ~0u,  // no _weak_field_map_
  PROTOBUF_FIELD_OFFSET(::game::GameParams, game_atlas_filename_),
  PROTOBUF_FIELD_OFFSET(::game::GameParams, dungen_params_filename_),
  PROTOBUF_FIELD_OFFSET(::game::GameParams, room_templates_filename_),
  PROTOBUF_FIELD_OFFSET(::game::GameParams, tilesize_),
  ~0u,  // no _has_bits_
  PROTOBUF_FIELD_OFFSET(::game::DungenParams, _internal_metadata_),
  ~0u,  // no _extensions_
  ~0u,  // no _oneof_case_
  ~0u,  // no _weak_field_map_
  PROTOBUF_FIELD_OFFSET(::game::DungenParams, room_count_),
  PROTOBUF_FIELD_OFFSET(::game::DungenParams, min_room_size_),
  PROTOBUF_FIELD_OFFSET(::game::DungenParams, max_room_size_),
  PROTOBUF_FIELD_OFFSET(::game::DungenParams, map_width_),
  PROTOBUF_FIELD_OFFSET(::game::DungenParams, map_height_),
  PROTOBUF_FIELD_OFFSET(::game::DungenParams, expand_chance_),
  ~0u,  // no _has_bits_
  PROTOBUF_FIELD_OFFSET(::game::ActionBinds, _internal_metadata_),
  ~0u,  // no _extensions_
  ~0u,  // no _oneof_case_
  ~0u,  // no _weak_field_map_
  PROTOBUF_FIELD_OFFSET(::game::ActionBinds, action_binds_),
};
static const ::PROTOBUF_NAMESPACE_ID::internal::MigrationSchema schemas[] PROTOBUF_SECTION_VARIABLE(protodesc_cold) = {
  { 0, -1, sizeof(::game::ActionBindEntry)},
  { 7, -1, sizeof(::game::GameParams)},
  { 16, -1, sizeof(::game::DungenParams)},
  { 27, -1, sizeof(::game::ActionBinds)},
};

static ::PROTOBUF_NAMESPACE_ID::Message const * const file_default_instances[] = {
  reinterpret_cast<const ::PROTOBUF_NAMESPACE_ID::Message*>(&::game::_ActionBindEntry_default_instance_),
  reinterpret_cast<const ::PROTOBUF_NAMESPACE_ID::Message*>(&::game::_GameParams_default_instance_),
  reinterpret_cast<const ::PROTOBUF_NAMESPACE_ID::Message*>(&::game::_DungenParams_default_instance_),
  reinterpret_cast<const ::PROTOBUF_NAMESPACE_ID::Message*>(&::game::_ActionBinds_default_instance_),
};

const char descriptor_table_protodef_proto_2fgame_2eproto[] PROTOBUF_SECTION_VARIABLE(protodesc_cold) =
  "\n\020proto/game.proto\022\004game\"\220\020\n\017ActionBindE"
  "ntry\022,\n\006action\030\001 \001(\0162\034.game.ActionBindEn"
  "try.Action\022(\n\004bind\030\002 \001(\0162\032.game.ActionBi"
  "ndEntry.Bind\"\273\001\n\006Action\022\022\n\016ACTION_UNKNOW"
  "N\020\000\022\010\n\004QUIT\020\001\022\010\n\004MENU\020\002\022\r\n\tDEBUG_HUD\020\003\022\n"
  "\n\006MOVE_N\020\004\022\013\n\007MOVE_NE\020\005\022\n\n\006MOVE_E\020\006\022\013\n\007M"
  "OVE_SE\020\007\022\n\n\006MOVE_S\020\010\022\013\n\007MOVE_SW\020\t\022\n\n\006MOV"
  "E_W\020\n\022\013\n\007MOVE_NW\020\013\022\014\n\010INTERACT\020\014\022\010\n\004WAIT"
  "\020\r\"\346\r\n\004Bind\022\020\n\014BIND_UNKNOWN\020\000\022\r\n\tKEY_SPA"
  "CE\020 \022\022\n\016KEY_APOSTROPHE\020\'\022\r\n\tKEY_COMMA\020,\022"
  "\r\n\tKEY_MINUS\020-\022\016\n\nKEY_PERIOD\020.\022\r\n\tKEY_SL"
  "ASH\020/\022\t\n\005KEY_0\0200\022\t\n\005KEY_1\0201\022\t\n\005KEY_2\0202\022\t"
  "\n\005KEY_3\0203\022\t\n\005KEY_4\0204\022\t\n\005KEY_5\0205\022\t\n\005KEY_6"
  "\0206\022\t\n\005KEY_7\0207\022\t\n\005KEY_8\0208\022\t\n\005KEY_9\0209\022\021\n\rK"
  "EY_SEMICOLON\020;\022\r\n\tKEY_EQUAL\020=\022\t\n\005KEY_A\020A"
  "\022\t\n\005KEY_B\020B\022\t\n\005KEY_C\020C\022\t\n\005KEY_D\020D\022\t\n\005KEY"
  "_E\020E\022\t\n\005KEY_F\020F\022\t\n\005KEY_G\020G\022\t\n\005KEY_H\020H\022\t\n"
  "\005KEY_I\020I\022\t\n\005KEY_J\020J\022\t\n\005KEY_K\020K\022\t\n\005KEY_L\020"
  "L\022\t\n\005KEY_M\020M\022\t\n\005KEY_N\020N\022\t\n\005KEY_O\020O\022\t\n\005KE"
  "Y_P\020P\022\t\n\005KEY_Q\020Q\022\t\n\005KEY_R\020R\022\t\n\005KEY_S\020S\022\t"
  "\n\005KEY_T\020T\022\t\n\005KEY_U\020U\022\t\n\005KEY_V\020V\022\t\n\005KEY_W"
  "\020W\022\t\n\005KEY_X\020X\022\t\n\005KEY_Y\020Y\022\t\n\005KEY_Z\020Z\022\024\n\020K"
  "EY_LEFT_BRACKET\020[\022\021\n\rKEY_BACKSLASH\020\\\022\025\n\021"
  "KEY_RIGHT_BRACKET\020]\022\024\n\020KEY_GRAVE_ACCENT\020"
  "`\022\017\n\nKEY_ESCAPE\020\200\002\022\016\n\tKEY_ENTER\020\201\002\022\014\n\007KE"
  "Y_TAB\020\202\002\022\022\n\rKEY_BACKSPACE\020\203\002\022\017\n\nKEY_INSE"
  "RT\020\204\002\022\017\n\nKEY_DELETE\020\205\002\022\016\n\tKEY_RIGHT\020\206\002\022\r"
  "\n\010KEY_LEFT\020\207\002\022\r\n\010KEY_DOWN\020\210\002\022\013\n\006KEY_UP\020\211"
  "\002\022\020\n\013KEY_PAGE_UP\020\212\002\022\022\n\rKEY_PAGE_DOWN\020\213\002\022"
  "\r\n\010KEY_HOME\020\214\002\022\014\n\007KEY_END\020\215\002\022\022\n\rKEY_CAPS"
  "_LOCK\020\230\002\022\024\n\017KEY_SCROLL_LOCK\020\231\002\022\021\n\014KEY_NU"
  "M_LOCK\020\232\002\022\025\n\020KEY_PRINT_SCREEN\020\233\002\022\016\n\tKEY_"
  "PAUSE\020\234\002\022\013\n\006KEY_F1\020\242\002\022\013\n\006KEY_F2\020\243\002\022\013\n\006KE"
  "Y_F3\020\244\002\022\013\n\006KEY_F4\020\245\002\022\013\n\006KEY_F5\020\246\002\022\013\n\006KEY"
  "_F6\020\247\002\022\013\n\006KEY_F7\020\250\002\022\013\n\006KEY_F8\020\251\002\022\013\n\006KEY_"
  "F9\020\252\002\022\014\n\007KEY_F10\020\253\002\022\014\n\007KEY_F11\020\254\002\022\014\n\007KEY"
  "_F12\020\255\002\022\014\n\007KEY_F13\020\256\002\022\014\n\007KEY_F14\020\257\002\022\014\n\007K"
  "EY_F15\020\260\002\022\014\n\007KEY_F16\020\261\002\022\014\n\007KEY_F17\020\262\002\022\014\n"
  "\007KEY_F18\020\263\002\022\014\n\007KEY_F19\020\264\002\022\014\n\007KEY_F20\020\265\002\022"
  "\014\n\007KEY_F21\020\266\002\022\014\n\007KEY_F22\020\267\002\022\014\n\007KEY_F23\020\270"
  "\002\022\014\n\007KEY_F24\020\271\002\022\014\n\007KEY_F25\020\272\002\022\r\n\010KEY_KP_"
  "0\020\300\002\022\r\n\010KEY_KP_1\020\301\002\022\r\n\010KEY_KP_2\020\302\002\022\r\n\010KE"
  "Y_KP_3\020\303\002\022\r\n\010KEY_KP_4\020\304\002\022\r\n\010KEY_KP_5\020\305\002\022"
  "\r\n\010KEY_KP_6\020\306\002\022\r\n\010KEY_KP_7\020\307\002\022\r\n\010KEY_KP_"
  "8\020\310\002\022\r\n\010KEY_KP_9\020\311\002\022\023\n\016KEY_KP_DECIMAL\020\312\002"
  "\022\022\n\rKEY_KP_DIVIDE\020\313\002\022\024\n\017KEY_KP_MULTIPLY\020"
  "\314\002\022\024\n\017KEY_KP_SUBTRACT\020\315\002\022\017\n\nKEY_KP_ADD\020\316"
  "\002\022\021\n\014KEY_KP_ENTER\020\317\002\022\021\n\014KEY_KP_EQUAL\020\320\002\022"
  "\023\n\016KEY_LEFT_SHIFT\020\324\002\022\025\n\020KEY_LEFT_CONTROL"
  "\020\325\002\022\021\n\014KEY_LEFT_ALT\020\326\002\022\023\n\016KEY_LEFT_SUPER"
  "\020\327\002\022\024\n\017KEY_RIGHT_SHIFT\020\330\002\022\026\n\021KEY_RIGHT_C"
  "ONTROL\020\331\002\022\022\n\rKEY_RIGHT_ALT\020\332\002\022\024\n\017KEY_RIG"
  "HT_SUPER\020\333\002\"|\n\nGameParams\022\033\n\023game_atlas_"
  "filename\030\001 \001(\t\022\036\n\026dungen_params_filename"
  "\030\002 \001(\t\022\037\n\027room_templates_filename\030\003 \001(\t\022"
  "\020\n\010tilesize\030\004 \001(\005\"\216\001\n\014DungenParams\022\022\n\nro"
  "om_count\030\001 \001(\005\022\025\n\rmin_room_size\030\002 \001(\005\022\025\n"
  "\rmax_room_size\030\003 \001(\005\022\021\n\tmap_width\030\004 \001(\005\022"
  "\022\n\nmap_height\030\005 \001(\005\022\025\n\rexpand_chance\030\006 \001"
  "(\005\":\n\013ActionBinds\022+\n\014action_binds\030\001 \003(\0132"
  "\025.game.ActionBindEntryb\006proto3"
  ;
static const ::PROTOBUF_NAMESPACE_ID::internal::DescriptorTable*const descriptor_table_proto_2fgame_2eproto_deps[1] = {
};
static ::PROTOBUF_NAMESPACE_ID::internal::SCCInfoBase*const descriptor_table_proto_2fgame_2eproto_sccs[4] = {
  &scc_info_ActionBindEntry_proto_2fgame_2eproto.base,
  &scc_info_ActionBinds_proto_2fgame_2eproto.base,
  &scc_info_DungenParams_proto_2fgame_2eproto.base,
  &scc_info_GameParams_proto_2fgame_2eproto.base,
};
static ::PROTOBUF_NAMESPACE_ID::internal::once_flag descriptor_table_proto_2fgame_2eproto_once;
const ::PROTOBUF_NAMESPACE_ID::internal::DescriptorTable descriptor_table_proto_2fgame_2eproto = {
  false, false, descriptor_table_protodef_proto_2fgame_2eproto, "proto/game.proto", 2430,
  &descriptor_table_proto_2fgame_2eproto_once, descriptor_table_proto_2fgame_2eproto_sccs, descriptor_table_proto_2fgame_2eproto_deps, 4, 0,
  schemas, file_default_instances, TableStruct_proto_2fgame_2eproto::offsets,
  file_level_metadata_proto_2fgame_2eproto, 4, file_level_enum_descriptors_proto_2fgame_2eproto, file_level_service_descriptors_proto_2fgame_2eproto,
};

// Force running AddDescriptors() at dynamic initialization time.
static bool dynamic_init_dummy_proto_2fgame_2eproto = (static_cast<void>(::PROTOBUF_NAMESPACE_ID::internal::AddDescriptors(&descriptor_table_proto_2fgame_2eproto)), true);
namespace game {
const ::PROTOBUF_NAMESPACE_ID::EnumDescriptor* ActionBindEntry_Action_descriptor() {
  ::PROTOBUF_NAMESPACE_ID::internal::AssignDescriptors(&descriptor_table_proto_2fgame_2eproto);
  return file_level_enum_descriptors_proto_2fgame_2eproto[0];
}
bool ActionBindEntry_Action_IsValid(int value) {
  switch (value) {
    case 0:
    case 1:
    case 2:
    case 3:
    case 4:
    case 5:
    case 6:
    case 7:
    case 8:
    case 9:
    case 10:
    case 11:
    case 12:
    case 13:
      return true;
    default:
      return false;
  }
}

#if (__cplusplus < 201703) && (!defined(_MSC_VER) || _MSC_VER >= 1900)
constexpr ActionBindEntry_Action ActionBindEntry::ACTION_UNKNOWN;
constexpr ActionBindEntry_Action ActionBindEntry::QUIT;
constexpr ActionBindEntry_Action ActionBindEntry::MENU;
constexpr ActionBindEntry_Action ActionBindEntry::DEBUG_HUD;
constexpr ActionBindEntry_Action ActionBindEntry::MOVE_N;
constexpr ActionBindEntry_Action ActionBindEntry::MOVE_NE;
constexpr ActionBindEntry_Action ActionBindEntry::MOVE_E;
constexpr ActionBindEntry_Action ActionBindEntry::MOVE_SE;
constexpr ActionBindEntry_Action ActionBindEntry::MOVE_S;
constexpr ActionBindEntry_Action ActionBindEntry::MOVE_SW;
constexpr ActionBindEntry_Action ActionBindEntry::MOVE_W;
constexpr ActionBindEntry_Action ActionBindEntry::MOVE_NW;
constexpr ActionBindEntry_Action ActionBindEntry::INTERACT;
constexpr ActionBindEntry_Action ActionBindEntry::WAIT;
constexpr ActionBindEntry_Action ActionBindEntry::Action_MIN;
constexpr ActionBindEntry_Action ActionBindEntry::Action_MAX;
constexpr int ActionBindEntry::Action_ARRAYSIZE;
#endif  // (__cplusplus < 201703) && (!defined(_MSC_VER) || _MSC_VER >= 1900)
const ::PROTOBUF_NAMESPACE_ID::EnumDescriptor* ActionBindEntry_Bind_descriptor() {
  ::PROTOBUF_NAMESPACE_ID::internal::AssignDescriptors(&descriptor_table_proto_2fgame_2eproto);
  return file_level_enum_descriptors_proto_2fgame_2eproto[1];
}
bool ActionBindEntry_Bind_IsValid(int value) {
  switch (value) {
    case 0:
    case 32:
    case 39:
    case 44:
    case 45:
    case 46:
    case 47:
    case 48:
    case 49:
    case 50:
    case 51:
    case 52:
    case 53:
    case 54:
    case 55:
    case 56:
    case 57:
    case 59:
    case 61:
    case 65:
    case 66:
    case 67:
    case 68:
    case 69:
    case 70:
    case 71:
    case 72:
    case 73:
    case 74:
    case 75:
    case 76:
    case 77:
    case 78:
    case 79:
    case 80:
    case 81:
    case 82:
    case 83:
    case 84:
    case 85:
    case 86:
    case 87:
    case 88:
    case 89:
    case 90:
    case 91:
    case 92:
    case 93:
    case 96:
    case 256:
    case 257:
    case 258:
    case 259:
    case 260:
    case 261:
    case 262:
    case 263:
    case 264:
    case 265:
    case 266:
    case 267:
    case 268:
    case 269:
    case 280:
    case 281:
    case 282:
    case 283:
    case 284:
    case 290:
    case 291:
    case 292:
    case 293:
    case 294:
    case 295:
    case 296:
    case 297:
    case 298:
    case 299:
    case 300:
    case 301:
    case 302:
    case 303:
    case 304:
    case 305:
    case 306:
    case 307:
    case 308:
    case 309:
    case 310:
    case 311:
    case 312:
    case 313:
    case 314:
    case 320:
    case 321:
    case 322:
    case 323:
    case 324:
    case 325:
    case 326:
    case 327:
    case 328:
    case 329:
    case 330:
    case 331:
    case 332:
    case 333:
    case 334:
    case 335:
    case 336:
    case 340:
    case 341:
    case 342:
    case 343:
    case 344:
    case 345:
    case 346:
    case 347:
      return true;
    default:
      return false;
  }
}

#if (__cplusplus < 201703) && (!defined(_MSC_VER) || _MSC_VER >= 1900)
constexpr ActionBindEntry_Bind ActionBindEntry::BIND_UNKNOWN;
constexpr ActionBindEntry_Bind ActionBindEntry::KEY_SPACE;
constexpr ActionBindEntry_Bind ActionBindEntry::KEY_APOSTROPHE;
constexpr ActionBindEntry_Bind ActionBindEntry::KEY_COMMA;
constexpr ActionBindEntry_Bind ActionBindEntry::KEY_MINUS;
constexpr ActionBindEntry_Bind ActionBindEntry::KEY_PERIOD;
constexpr ActionBindEntry_Bind ActionBindEntry::KEY_SLASH;
constexpr ActionBindEntry_Bind ActionBindEntry::KEY_0;
constexpr ActionBindEntry_Bind ActionBindEntry::KEY_1;
constexpr ActionBindEntry_Bind ActionBindEntry::KEY_2;
constexpr ActionBindEntry_Bind ActionBindEntry::KEY_3;
constexpr ActionBindEntry_Bind ActionBindEntry::KEY_4;
constexpr ActionBindEntry_Bind ActionBindEntry::KEY_5;
constexpr ActionBindEntry_Bind ActionBindEntry::KEY_6;
constexpr ActionBindEntry_Bind ActionBindEntry::KEY_7;
constexpr ActionBindEntry_Bind ActionBindEntry::KEY_8;
constexpr ActionBindEntry_Bind ActionBindEntry::KEY_9;
constexpr ActionBindEntry_Bind ActionBindEntry::KEY_SEMICOLON;
constexpr ActionBindEntry_Bind ActionBindEntry::KEY_EQUAL;
constexpr ActionBindEntry_Bind ActionBindEntry::KEY_A;
constexpr ActionBindEntry_Bind ActionBindEntry::KEY_B;
constexpr ActionBindEntry_Bind ActionBindEntry::KEY_C;
constexpr ActionBindEntry_Bind ActionBindEntry::KEY_D;
constexpr ActionBindEntry_Bind ActionBindEntry::KEY_E;
constexpr ActionBindEntry_Bind ActionBindEntry::KEY_F;
constexpr ActionBindEntry_Bind ActionBindEntry::KEY_G;
constexpr ActionBindEntry_Bind ActionBindEntry::KEY_H;
constexpr ActionBindEntry_Bind ActionBindEntry::KEY_I;
constexpr ActionBindEntry_Bind ActionBindEntry::KEY_J;
constexpr ActionBindEntry_Bind ActionBindEntry::KEY_K;
constexpr ActionBindEntry_Bind ActionBindEntry::KEY_L;
constexpr ActionBindEntry_Bind ActionBindEntry::KEY_M;
constexpr ActionBindEntry_Bind ActionBindEntry::KEY_N;
constexpr ActionBindEntry_Bind ActionBindEntry::KEY_O;
constexpr ActionBindEntry_Bind ActionBindEntry::KEY_P;
constexpr ActionBindEntry_Bind ActionBindEntry::KEY_Q;
constexpr ActionBindEntry_Bind ActionBindEntry::KEY_R;
constexpr ActionBindEntry_Bind ActionBindEntry::KEY_S;
constexpr ActionBindEntry_Bind ActionBindEntry::KEY_T;
constexpr ActionBindEntry_Bind ActionBindEntry::KEY_U;
constexpr ActionBindEntry_Bind ActionBindEntry::KEY_V;
constexpr ActionBindEntry_Bind ActionBindEntry::KEY_W;
constexpr ActionBindEntry_Bind ActionBindEntry::KEY_X;
constexpr ActionBindEntry_Bind ActionBindEntry::KEY_Y;
constexpr ActionBindEntry_Bind ActionBindEntry::KEY_Z;
constexpr ActionBindEntry_Bind ActionBindEntry::KEY_LEFT_BRACKET;
constexpr ActionBindEntry_Bind ActionBindEntry::KEY_BACKSLASH;
constexpr ActionBindEntry_Bind ActionBindEntry::KEY_RIGHT_BRACKET;
constexpr ActionBindEntry_Bind ActionBindEntry::KEY_GRAVE_ACCENT;
constexpr ActionBindEntry_Bind ActionBindEntry::KEY_ESCAPE;
constexpr ActionBindEntry_Bind ActionBindEntry::KEY_ENTER;
constexpr ActionBindEntry_Bind ActionBindEntry::KEY_TAB;
constexpr ActionBindEntry_Bind ActionBindEntry::KEY_BACKSPACE;
constexpr ActionBindEntry_Bind ActionBindEntry::KEY_INSERT;
constexpr ActionBindEntry_Bind ActionBindEntry::KEY_DELETE;
constexpr ActionBindEntry_Bind ActionBindEntry::KEY_RIGHT;
constexpr ActionBindEntry_Bind ActionBindEntry::KEY_LEFT;
constexpr ActionBindEntry_Bind ActionBindEntry::KEY_DOWN;
constexpr ActionBindEntry_Bind ActionBindEntry::KEY_UP;
constexpr ActionBindEntry_Bind ActionBindEntry::KEY_PAGE_UP;
constexpr ActionBindEntry_Bind ActionBindEntry::KEY_PAGE_DOWN;
constexpr ActionBindEntry_Bind ActionBindEntry::KEY_HOME;
constexpr ActionBindEntry_Bind ActionBindEntry::KEY_END;
constexpr ActionBindEntry_Bind ActionBindEntry::KEY_CAPS_LOCK;
constexpr ActionBindEntry_Bind ActionBindEntry::KEY_SCROLL_LOCK;
constexpr ActionBindEntry_Bind ActionBindEntry::KEY_NUM_LOCK;
constexpr ActionBindEntry_Bind ActionBindEntry::KEY_PRINT_SCREEN;
constexpr ActionBindEntry_Bind ActionBindEntry::KEY_PAUSE;
constexpr ActionBindEntry_Bind ActionBindEntry::KEY_F1;
constexpr ActionBindEntry_Bind ActionBindEntry::KEY_F2;
constexpr ActionBindEntry_Bind ActionBindEntry::KEY_F3;
constexpr ActionBindEntry_Bind ActionBindEntry::KEY_F4;
constexpr ActionBindEntry_Bind ActionBindEntry::KEY_F5;
constexpr ActionBindEntry_Bind ActionBindEntry::KEY_F6;
constexpr ActionBindEntry_Bind ActionBindEntry::KEY_F7;
constexpr ActionBindEntry_Bind ActionBindEntry::KEY_F8;
constexpr ActionBindEntry_Bind ActionBindEntry::KEY_F9;
constexpr ActionBindEntry_Bind ActionBindEntry::KEY_F10;
constexpr ActionBindEntry_Bind ActionBindEntry::KEY_F11;
constexpr ActionBindEntry_Bind ActionBindEntry::KEY_F12;
constexpr ActionBindEntry_Bind ActionBindEntry::KEY_F13;
constexpr ActionBindEntry_Bind ActionBindEntry::KEY_F14;
constexpr ActionBindEntry_Bind ActionBindEntry::KEY_F15;
constexpr ActionBindEntry_Bind ActionBindEntry::KEY_F16;
constexpr ActionBindEntry_Bind ActionBindEntry::KEY_F17;
constexpr ActionBindEntry_Bind ActionBindEntry::KEY_F18;
constexpr ActionBindEntry_Bind ActionBindEntry::KEY_F19;
constexpr ActionBindEntry_Bind ActionBindEntry::KEY_F20;
constexpr ActionBindEntry_Bind ActionBindEntry::KEY_F21;
constexpr ActionBindEntry_Bind ActionBindEntry::KEY_F22;
constexpr ActionBindEntry_Bind ActionBindEntry::KEY_F23;
constexpr ActionBindEntry_Bind ActionBindEntry::KEY_F24;
constexpr ActionBindEntry_Bind ActionBindEntry::KEY_F25;
constexpr ActionBindEntry_Bind ActionBindEntry::KEY_KP_0;
constexpr ActionBindEntry_Bind ActionBindEntry::KEY_KP_1;
constexpr ActionBindEntry_Bind ActionBindEntry::KEY_KP_2;
constexpr ActionBindEntry_Bind ActionBindEntry::KEY_KP_3;
constexpr ActionBindEntry_Bind ActionBindEntry::KEY_KP_4;
constexpr ActionBindEntry_Bind ActionBindEntry::KEY_KP_5;
constexpr ActionBindEntry_Bind ActionBindEntry::KEY_KP_6;
constexpr ActionBindEntry_Bind ActionBindEntry::KEY_KP_7;
constexpr ActionBindEntry_Bind ActionBindEntry::KEY_KP_8;
constexpr ActionBindEntry_Bind ActionBindEntry::KEY_KP_9;
constexpr ActionBindEntry_Bind ActionBindEntry::KEY_KP_DECIMAL;
constexpr ActionBindEntry_Bind ActionBindEntry::KEY_KP_DIVIDE;
constexpr ActionBindEntry_Bind ActionBindEntry::KEY_KP_MULTIPLY;
constexpr ActionBindEntry_Bind ActionBindEntry::KEY_KP_SUBTRACT;
constexpr ActionBindEntry_Bind ActionBindEntry::KEY_KP_ADD;
constexpr ActionBindEntry_Bind ActionBindEntry::KEY_KP_ENTER;
constexpr ActionBindEntry_Bind ActionBindEntry::KEY_KP_EQUAL;
constexpr ActionBindEntry_Bind ActionBindEntry::KEY_LEFT_SHIFT;
constexpr ActionBindEntry_Bind ActionBindEntry::KEY_LEFT_CONTROL;
constexpr ActionBindEntry_Bind ActionBindEntry::KEY_LEFT_ALT;
constexpr ActionBindEntry_Bind ActionBindEntry::KEY_LEFT_SUPER;
constexpr ActionBindEntry_Bind ActionBindEntry::KEY_RIGHT_SHIFT;
constexpr ActionBindEntry_Bind ActionBindEntry::KEY_RIGHT_CONTROL;
constexpr ActionBindEntry_Bind ActionBindEntry::KEY_RIGHT_ALT;
constexpr ActionBindEntry_Bind ActionBindEntry::KEY_RIGHT_SUPER;
constexpr ActionBindEntry_Bind ActionBindEntry::Bind_MIN;
constexpr ActionBindEntry_Bind ActionBindEntry::Bind_MAX;
constexpr int ActionBindEntry::Bind_ARRAYSIZE;
#endif  // (__cplusplus < 201703) && (!defined(_MSC_VER) || _MSC_VER >= 1900)

// ===================================================================

class ActionBindEntry::_Internal {
 public:
};

ActionBindEntry::ActionBindEntry(::PROTOBUF_NAMESPACE_ID::Arena* arena)
  : ::PROTOBUF_NAMESPACE_ID::Message(arena) {
  SharedCtor();
  RegisterArenaDtor(arena);
  // @@protoc_insertion_point(arena_constructor:game.ActionBindEntry)
}
ActionBindEntry::ActionBindEntry(const ActionBindEntry& from)
  : ::PROTOBUF_NAMESPACE_ID::Message() {
  _internal_metadata_.MergeFrom<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>(from._internal_metadata_);
  ::memcpy(&action_, &from.action_,
    static_cast<size_t>(reinterpret_cast<char*>(&bind_) -
    reinterpret_cast<char*>(&action_)) + sizeof(bind_));
  // @@protoc_insertion_point(copy_constructor:game.ActionBindEntry)
}

void ActionBindEntry::SharedCtor() {
  ::memset(reinterpret_cast<char*>(this) + static_cast<size_t>(
      reinterpret_cast<char*>(&action_) - reinterpret_cast<char*>(this)),
      0, static_cast<size_t>(reinterpret_cast<char*>(&bind_) -
      reinterpret_cast<char*>(&action_)) + sizeof(bind_));
}

ActionBindEntry::~ActionBindEntry() {
  // @@protoc_insertion_point(destructor:game.ActionBindEntry)
  SharedDtor();
  _internal_metadata_.Delete<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>();
}

void ActionBindEntry::SharedDtor() {
  GOOGLE_DCHECK(GetArena() == nullptr);
}

void ActionBindEntry::ArenaDtor(void* object) {
  ActionBindEntry* _this = reinterpret_cast< ActionBindEntry* >(object);
  (void)_this;
}
void ActionBindEntry::RegisterArenaDtor(::PROTOBUF_NAMESPACE_ID::Arena*) {
}
void ActionBindEntry::SetCachedSize(int size) const {
  _cached_size_.Set(size);
}
const ActionBindEntry& ActionBindEntry::default_instance() {
  ::PROTOBUF_NAMESPACE_ID::internal::InitSCC(&::scc_info_ActionBindEntry_proto_2fgame_2eproto.base);
  return *internal_default_instance();
}


void ActionBindEntry::Clear() {
// @@protoc_insertion_point(message_clear_start:game.ActionBindEntry)
  ::PROTOBUF_NAMESPACE_ID::uint32 cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void) cached_has_bits;

  ::memset(&action_, 0, static_cast<size_t>(
      reinterpret_cast<char*>(&bind_) -
      reinterpret_cast<char*>(&action_)) + sizeof(bind_));
  _internal_metadata_.Clear<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>();
}

const char* ActionBindEntry::_InternalParse(const char* ptr, ::PROTOBUF_NAMESPACE_ID::internal::ParseContext* ctx) {
#define CHK_(x) if (PROTOBUF_PREDICT_FALSE(!(x))) goto failure
  while (!ctx->Done(&ptr)) {
    ::PROTOBUF_NAMESPACE_ID::uint32 tag;
    ptr = ::PROTOBUF_NAMESPACE_ID::internal::ReadTag(ptr, &tag);
    CHK_(ptr);
    switch (tag >> 3) {
      // .game.ActionBindEntry.Action action = 1;
      case 1:
        if (PROTOBUF_PREDICT_TRUE(static_cast<::PROTOBUF_NAMESPACE_ID::uint8>(tag) == 8)) {
          ::PROTOBUF_NAMESPACE_ID::uint64 val = ::PROTOBUF_NAMESPACE_ID::internal::ReadVarint64(&ptr);
          CHK_(ptr);
          _internal_set_action(static_cast<::game::ActionBindEntry_Action>(val));
        } else goto handle_unusual;
        continue;
      // .game.ActionBindEntry.Bind bind = 2;
      case 2:
        if (PROTOBUF_PREDICT_TRUE(static_cast<::PROTOBUF_NAMESPACE_ID::uint8>(tag) == 16)) {
          ::PROTOBUF_NAMESPACE_ID::uint64 val = ::PROTOBUF_NAMESPACE_ID::internal::ReadVarint64(&ptr);
          CHK_(ptr);
          _internal_set_bind(static_cast<::game::ActionBindEntry_Bind>(val));
        } else goto handle_unusual;
        continue;
      default: {
      handle_unusual:
        if ((tag & 7) == 4 || tag == 0) {
          ctx->SetLastTag(tag);
          goto success;
        }
        ptr = UnknownFieldParse(tag,
            _internal_metadata_.mutable_unknown_fields<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>(),
            ptr, ctx);
        CHK_(ptr != nullptr);
        continue;
      }
    }  // switch
  }  // while
success:
  return ptr;
failure:
  ptr = nullptr;
  goto success;
#undef CHK_
}

::PROTOBUF_NAMESPACE_ID::uint8* ActionBindEntry::_InternalSerialize(
    ::PROTOBUF_NAMESPACE_ID::uint8* target, ::PROTOBUF_NAMESPACE_ID::io::EpsCopyOutputStream* stream) const {
  // @@protoc_insertion_point(serialize_to_array_start:game.ActionBindEntry)
  ::PROTOBUF_NAMESPACE_ID::uint32 cached_has_bits = 0;
  (void) cached_has_bits;

  // .game.ActionBindEntry.Action action = 1;
  if (this->action() != 0) {
    target = stream->EnsureSpace(target);
    target = ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::WriteEnumToArray(
      1, this->_internal_action(), target);
  }

  // .game.ActionBindEntry.Bind bind = 2;
  if (this->bind() != 0) {
    target = stream->EnsureSpace(target);
    target = ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::WriteEnumToArray(
      2, this->_internal_bind(), target);
  }

  if (PROTOBUF_PREDICT_FALSE(_internal_metadata_.have_unknown_fields())) {
    target = ::PROTOBUF_NAMESPACE_ID::internal::WireFormat::InternalSerializeUnknownFieldsToArray(
        _internal_metadata_.unknown_fields<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>(::PROTOBUF_NAMESPACE_ID::UnknownFieldSet::default_instance), target, stream);
  }
  // @@protoc_insertion_point(serialize_to_array_end:game.ActionBindEntry)
  return target;
}

size_t ActionBindEntry::ByteSizeLong() const {
// @@protoc_insertion_point(message_byte_size_start:game.ActionBindEntry)
  size_t total_size = 0;

  ::PROTOBUF_NAMESPACE_ID::uint32 cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void) cached_has_bits;

  // .game.ActionBindEntry.Action action = 1;
  if (this->action() != 0) {
    total_size += 1 +
      ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::EnumSize(this->_internal_action());
  }

  // .game.ActionBindEntry.Bind bind = 2;
  if (this->bind() != 0) {
    total_size += 1 +
      ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::EnumSize(this->_internal_bind());
  }

  if (PROTOBUF_PREDICT_FALSE(_internal_metadata_.have_unknown_fields())) {
    return ::PROTOBUF_NAMESPACE_ID::internal::ComputeUnknownFieldsSize(
        _internal_metadata_, total_size, &_cached_size_);
  }
  int cached_size = ::PROTOBUF_NAMESPACE_ID::internal::ToCachedSize(total_size);
  SetCachedSize(cached_size);
  return total_size;
}

void ActionBindEntry::MergeFrom(const ::PROTOBUF_NAMESPACE_ID::Message& from) {
// @@protoc_insertion_point(generalized_merge_from_start:game.ActionBindEntry)
  GOOGLE_DCHECK_NE(&from, this);
  const ActionBindEntry* source =
      ::PROTOBUF_NAMESPACE_ID::DynamicCastToGenerated<ActionBindEntry>(
          &from);
  if (source == nullptr) {
  // @@protoc_insertion_point(generalized_merge_from_cast_fail:game.ActionBindEntry)
    ::PROTOBUF_NAMESPACE_ID::internal::ReflectionOps::Merge(from, this);
  } else {
  // @@protoc_insertion_point(generalized_merge_from_cast_success:game.ActionBindEntry)
    MergeFrom(*source);
  }
}

void ActionBindEntry::MergeFrom(const ActionBindEntry& from) {
// @@protoc_insertion_point(class_specific_merge_from_start:game.ActionBindEntry)
  GOOGLE_DCHECK_NE(&from, this);
  _internal_metadata_.MergeFrom<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>(from._internal_metadata_);
  ::PROTOBUF_NAMESPACE_ID::uint32 cached_has_bits = 0;
  (void) cached_has_bits;

  if (from.action() != 0) {
    _internal_set_action(from._internal_action());
  }
  if (from.bind() != 0) {
    _internal_set_bind(from._internal_bind());
  }
}

void ActionBindEntry::CopyFrom(const ::PROTOBUF_NAMESPACE_ID::Message& from) {
// @@protoc_insertion_point(generalized_copy_from_start:game.ActionBindEntry)
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}

void ActionBindEntry::CopyFrom(const ActionBindEntry& from) {
// @@protoc_insertion_point(class_specific_copy_from_start:game.ActionBindEntry)
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}

bool ActionBindEntry::IsInitialized() const {
  return true;
}

void ActionBindEntry::InternalSwap(ActionBindEntry* other) {
  using std::swap;
  _internal_metadata_.Swap<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>(&other->_internal_metadata_);
  ::PROTOBUF_NAMESPACE_ID::internal::memswap<
      PROTOBUF_FIELD_OFFSET(ActionBindEntry, bind_)
      + sizeof(ActionBindEntry::bind_)
      - PROTOBUF_FIELD_OFFSET(ActionBindEntry, action_)>(
          reinterpret_cast<char*>(&action_),
          reinterpret_cast<char*>(&other->action_));
}

::PROTOBUF_NAMESPACE_ID::Metadata ActionBindEntry::GetMetadata() const {
  return GetMetadataStatic();
}


// ===================================================================

class GameParams::_Internal {
 public:
};

GameParams::GameParams(::PROTOBUF_NAMESPACE_ID::Arena* arena)
  : ::PROTOBUF_NAMESPACE_ID::Message(arena) {
  SharedCtor();
  RegisterArenaDtor(arena);
  // @@protoc_insertion_point(arena_constructor:game.GameParams)
}
GameParams::GameParams(const GameParams& from)
  : ::PROTOBUF_NAMESPACE_ID::Message() {
  _internal_metadata_.MergeFrom<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>(from._internal_metadata_);
  game_atlas_filename_.UnsafeSetDefault(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited());
  if (!from._internal_game_atlas_filename().empty()) {
    game_atlas_filename_.Set(::PROTOBUF_NAMESPACE_ID::internal::ArenaStringPtr::EmptyDefault{}, from._internal_game_atlas_filename(), 
      GetArena());
  }
  dungen_params_filename_.UnsafeSetDefault(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited());
  if (!from._internal_dungen_params_filename().empty()) {
    dungen_params_filename_.Set(::PROTOBUF_NAMESPACE_ID::internal::ArenaStringPtr::EmptyDefault{}, from._internal_dungen_params_filename(), 
      GetArena());
  }
  room_templates_filename_.UnsafeSetDefault(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited());
  if (!from._internal_room_templates_filename().empty()) {
    room_templates_filename_.Set(::PROTOBUF_NAMESPACE_ID::internal::ArenaStringPtr::EmptyDefault{}, from._internal_room_templates_filename(), 
      GetArena());
  }
  tilesize_ = from.tilesize_;
  // @@protoc_insertion_point(copy_constructor:game.GameParams)
}

void GameParams::SharedCtor() {
  ::PROTOBUF_NAMESPACE_ID::internal::InitSCC(&scc_info_GameParams_proto_2fgame_2eproto.base);
  game_atlas_filename_.UnsafeSetDefault(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited());
  dungen_params_filename_.UnsafeSetDefault(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited());
  room_templates_filename_.UnsafeSetDefault(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited());
  tilesize_ = 0;
}

GameParams::~GameParams() {
  // @@protoc_insertion_point(destructor:game.GameParams)
  SharedDtor();
  _internal_metadata_.Delete<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>();
}

void GameParams::SharedDtor() {
  GOOGLE_DCHECK(GetArena() == nullptr);
  game_atlas_filename_.DestroyNoArena(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited());
  dungen_params_filename_.DestroyNoArena(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited());
  room_templates_filename_.DestroyNoArena(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited());
}

void GameParams::ArenaDtor(void* object) {
  GameParams* _this = reinterpret_cast< GameParams* >(object);
  (void)_this;
}
void GameParams::RegisterArenaDtor(::PROTOBUF_NAMESPACE_ID::Arena*) {
}
void GameParams::SetCachedSize(int size) const {
  _cached_size_.Set(size);
}
const GameParams& GameParams::default_instance() {
  ::PROTOBUF_NAMESPACE_ID::internal::InitSCC(&::scc_info_GameParams_proto_2fgame_2eproto.base);
  return *internal_default_instance();
}


void GameParams::Clear() {
// @@protoc_insertion_point(message_clear_start:game.GameParams)
  ::PROTOBUF_NAMESPACE_ID::uint32 cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void) cached_has_bits;

  game_atlas_filename_.ClearToEmpty();
  dungen_params_filename_.ClearToEmpty();
  room_templates_filename_.ClearToEmpty();
  tilesize_ = 0;
  _internal_metadata_.Clear<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>();
}

const char* GameParams::_InternalParse(const char* ptr, ::PROTOBUF_NAMESPACE_ID::internal::ParseContext* ctx) {
#define CHK_(x) if (PROTOBUF_PREDICT_FALSE(!(x))) goto failure
  while (!ctx->Done(&ptr)) {
    ::PROTOBUF_NAMESPACE_ID::uint32 tag;
    ptr = ::PROTOBUF_NAMESPACE_ID::internal::ReadTag(ptr, &tag);
    CHK_(ptr);
    switch (tag >> 3) {
      // string game_atlas_filename = 1;
      case 1:
        if (PROTOBUF_PREDICT_TRUE(static_cast<::PROTOBUF_NAMESPACE_ID::uint8>(tag) == 10)) {
          auto str = _internal_mutable_game_atlas_filename();
          ptr = ::PROTOBUF_NAMESPACE_ID::internal::InlineGreedyStringParser(str, ptr, ctx);
          CHK_(::PROTOBUF_NAMESPACE_ID::internal::VerifyUTF8(str, "game.GameParams.game_atlas_filename"));
          CHK_(ptr);
        } else goto handle_unusual;
        continue;
      // string dungen_params_filename = 2;
      case 2:
        if (PROTOBUF_PREDICT_TRUE(static_cast<::PROTOBUF_NAMESPACE_ID::uint8>(tag) == 18)) {
          auto str = _internal_mutable_dungen_params_filename();
          ptr = ::PROTOBUF_NAMESPACE_ID::internal::InlineGreedyStringParser(str, ptr, ctx);
          CHK_(::PROTOBUF_NAMESPACE_ID::internal::VerifyUTF8(str, "game.GameParams.dungen_params_filename"));
          CHK_(ptr);
        } else goto handle_unusual;
        continue;
      // string room_templates_filename = 3;
      case 3:
        if (PROTOBUF_PREDICT_TRUE(static_cast<::PROTOBUF_NAMESPACE_ID::uint8>(tag) == 26)) {
          auto str = _internal_mutable_room_templates_filename();
          ptr = ::PROTOBUF_NAMESPACE_ID::internal::InlineGreedyStringParser(str, ptr, ctx);
          CHK_(::PROTOBUF_NAMESPACE_ID::internal::VerifyUTF8(str, "game.GameParams.room_templates_filename"));
          CHK_(ptr);
        } else goto handle_unusual;
        continue;
      // int32 tilesize = 4;
      case 4:
        if (PROTOBUF_PREDICT_TRUE(static_cast<::PROTOBUF_NAMESPACE_ID::uint8>(tag) == 32)) {
          tilesize_ = ::PROTOBUF_NAMESPACE_ID::internal::ReadVarint64(&ptr);
          CHK_(ptr);
        } else goto handle_unusual;
        continue;
      default: {
      handle_unusual:
        if ((tag & 7) == 4 || tag == 0) {
          ctx->SetLastTag(tag);
          goto success;
        }
        ptr = UnknownFieldParse(tag,
            _internal_metadata_.mutable_unknown_fields<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>(),
            ptr, ctx);
        CHK_(ptr != nullptr);
        continue;
      }
    }  // switch
  }  // while
success:
  return ptr;
failure:
  ptr = nullptr;
  goto success;
#undef CHK_
}

::PROTOBUF_NAMESPACE_ID::uint8* GameParams::_InternalSerialize(
    ::PROTOBUF_NAMESPACE_ID::uint8* target, ::PROTOBUF_NAMESPACE_ID::io::EpsCopyOutputStream* stream) const {
  // @@protoc_insertion_point(serialize_to_array_start:game.GameParams)
  ::PROTOBUF_NAMESPACE_ID::uint32 cached_has_bits = 0;
  (void) cached_has_bits;

  // string game_atlas_filename = 1;
  if (this->game_atlas_filename().size() > 0) {
    ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::VerifyUtf8String(
      this->_internal_game_atlas_filename().data(), static_cast<int>(this->_internal_game_atlas_filename().length()),
      ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::SERIALIZE,
      "game.GameParams.game_atlas_filename");
    target = stream->WriteStringMaybeAliased(
        1, this->_internal_game_atlas_filename(), target);
  }

  // string dungen_params_filename = 2;
  if (this->dungen_params_filename().size() > 0) {
    ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::VerifyUtf8String(
      this->_internal_dungen_params_filename().data(), static_cast<int>(this->_internal_dungen_params_filename().length()),
      ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::SERIALIZE,
      "game.GameParams.dungen_params_filename");
    target = stream->WriteStringMaybeAliased(
        2, this->_internal_dungen_params_filename(), target);
  }

  // string room_templates_filename = 3;
  if (this->room_templates_filename().size() > 0) {
    ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::VerifyUtf8String(
      this->_internal_room_templates_filename().data(), static_cast<int>(this->_internal_room_templates_filename().length()),
      ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::SERIALIZE,
      "game.GameParams.room_templates_filename");
    target = stream->WriteStringMaybeAliased(
        3, this->_internal_room_templates_filename(), target);
  }

  // int32 tilesize = 4;
  if (this->tilesize() != 0) {
    target = stream->EnsureSpace(target);
    target = ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::WriteInt32ToArray(4, this->_internal_tilesize(), target);
  }

  if (PROTOBUF_PREDICT_FALSE(_internal_metadata_.have_unknown_fields())) {
    target = ::PROTOBUF_NAMESPACE_ID::internal::WireFormat::InternalSerializeUnknownFieldsToArray(
        _internal_metadata_.unknown_fields<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>(::PROTOBUF_NAMESPACE_ID::UnknownFieldSet::default_instance), target, stream);
  }
  // @@protoc_insertion_point(serialize_to_array_end:game.GameParams)
  return target;
}

size_t GameParams::ByteSizeLong() const {
// @@protoc_insertion_point(message_byte_size_start:game.GameParams)
  size_t total_size = 0;

  ::PROTOBUF_NAMESPACE_ID::uint32 cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void) cached_has_bits;

  // string game_atlas_filename = 1;
  if (this->game_atlas_filename().size() > 0) {
    total_size += 1 +
      ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::StringSize(
        this->_internal_game_atlas_filename());
  }

  // string dungen_params_filename = 2;
  if (this->dungen_params_filename().size() > 0) {
    total_size += 1 +
      ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::StringSize(
        this->_internal_dungen_params_filename());
  }

  // string room_templates_filename = 3;
  if (this->room_templates_filename().size() > 0) {
    total_size += 1 +
      ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::StringSize(
        this->_internal_room_templates_filename());
  }

  // int32 tilesize = 4;
  if (this->tilesize() != 0) {
    total_size += 1 +
      ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::Int32Size(
        this->_internal_tilesize());
  }

  if (PROTOBUF_PREDICT_FALSE(_internal_metadata_.have_unknown_fields())) {
    return ::PROTOBUF_NAMESPACE_ID::internal::ComputeUnknownFieldsSize(
        _internal_metadata_, total_size, &_cached_size_);
  }
  int cached_size = ::PROTOBUF_NAMESPACE_ID::internal::ToCachedSize(total_size);
  SetCachedSize(cached_size);
  return total_size;
}

void GameParams::MergeFrom(const ::PROTOBUF_NAMESPACE_ID::Message& from) {
// @@protoc_insertion_point(generalized_merge_from_start:game.GameParams)
  GOOGLE_DCHECK_NE(&from, this);
  const GameParams* source =
      ::PROTOBUF_NAMESPACE_ID::DynamicCastToGenerated<GameParams>(
          &from);
  if (source == nullptr) {
  // @@protoc_insertion_point(generalized_merge_from_cast_fail:game.GameParams)
    ::PROTOBUF_NAMESPACE_ID::internal::ReflectionOps::Merge(from, this);
  } else {
  // @@protoc_insertion_point(generalized_merge_from_cast_success:game.GameParams)
    MergeFrom(*source);
  }
}

void GameParams::MergeFrom(const GameParams& from) {
// @@protoc_insertion_point(class_specific_merge_from_start:game.GameParams)
  GOOGLE_DCHECK_NE(&from, this);
  _internal_metadata_.MergeFrom<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>(from._internal_metadata_);
  ::PROTOBUF_NAMESPACE_ID::uint32 cached_has_bits = 0;
  (void) cached_has_bits;

  if (from.game_atlas_filename().size() > 0) {
    _internal_set_game_atlas_filename(from._internal_game_atlas_filename());
  }
  if (from.dungen_params_filename().size() > 0) {
    _internal_set_dungen_params_filename(from._internal_dungen_params_filename());
  }
  if (from.room_templates_filename().size() > 0) {
    _internal_set_room_templates_filename(from._internal_room_templates_filename());
  }
  if (from.tilesize() != 0) {
    _internal_set_tilesize(from._internal_tilesize());
  }
}

void GameParams::CopyFrom(const ::PROTOBUF_NAMESPACE_ID::Message& from) {
// @@protoc_insertion_point(generalized_copy_from_start:game.GameParams)
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}

void GameParams::CopyFrom(const GameParams& from) {
// @@protoc_insertion_point(class_specific_copy_from_start:game.GameParams)
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}

bool GameParams::IsInitialized() const {
  return true;
}

void GameParams::InternalSwap(GameParams* other) {
  using std::swap;
  _internal_metadata_.Swap<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>(&other->_internal_metadata_);
  game_atlas_filename_.Swap(&other->game_atlas_filename_, &::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited(), GetArena());
  dungen_params_filename_.Swap(&other->dungen_params_filename_, &::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited(), GetArena());
  room_templates_filename_.Swap(&other->room_templates_filename_, &::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited(), GetArena());
  swap(tilesize_, other->tilesize_);
}

::PROTOBUF_NAMESPACE_ID::Metadata GameParams::GetMetadata() const {
  return GetMetadataStatic();
}


// ===================================================================

class DungenParams::_Internal {
 public:
};

DungenParams::DungenParams(::PROTOBUF_NAMESPACE_ID::Arena* arena)
  : ::PROTOBUF_NAMESPACE_ID::Message(arena) {
  SharedCtor();
  RegisterArenaDtor(arena);
  // @@protoc_insertion_point(arena_constructor:game.DungenParams)
}
DungenParams::DungenParams(const DungenParams& from)
  : ::PROTOBUF_NAMESPACE_ID::Message() {
  _internal_metadata_.MergeFrom<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>(from._internal_metadata_);
  ::memcpy(&room_count_, &from.room_count_,
    static_cast<size_t>(reinterpret_cast<char*>(&expand_chance_) -
    reinterpret_cast<char*>(&room_count_)) + sizeof(expand_chance_));
  // @@protoc_insertion_point(copy_constructor:game.DungenParams)
}

void DungenParams::SharedCtor() {
  ::memset(reinterpret_cast<char*>(this) + static_cast<size_t>(
      reinterpret_cast<char*>(&room_count_) - reinterpret_cast<char*>(this)),
      0, static_cast<size_t>(reinterpret_cast<char*>(&expand_chance_) -
      reinterpret_cast<char*>(&room_count_)) + sizeof(expand_chance_));
}

DungenParams::~DungenParams() {
  // @@protoc_insertion_point(destructor:game.DungenParams)
  SharedDtor();
  _internal_metadata_.Delete<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>();
}

void DungenParams::SharedDtor() {
  GOOGLE_DCHECK(GetArena() == nullptr);
}

void DungenParams::ArenaDtor(void* object) {
  DungenParams* _this = reinterpret_cast< DungenParams* >(object);
  (void)_this;
}
void DungenParams::RegisterArenaDtor(::PROTOBUF_NAMESPACE_ID::Arena*) {
}
void DungenParams::SetCachedSize(int size) const {
  _cached_size_.Set(size);
}
const DungenParams& DungenParams::default_instance() {
  ::PROTOBUF_NAMESPACE_ID::internal::InitSCC(&::scc_info_DungenParams_proto_2fgame_2eproto.base);
  return *internal_default_instance();
}


void DungenParams::Clear() {
// @@protoc_insertion_point(message_clear_start:game.DungenParams)
  ::PROTOBUF_NAMESPACE_ID::uint32 cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void) cached_has_bits;

  ::memset(&room_count_, 0, static_cast<size_t>(
      reinterpret_cast<char*>(&expand_chance_) -
      reinterpret_cast<char*>(&room_count_)) + sizeof(expand_chance_));
  _internal_metadata_.Clear<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>();
}

const char* DungenParams::_InternalParse(const char* ptr, ::PROTOBUF_NAMESPACE_ID::internal::ParseContext* ctx) {
#define CHK_(x) if (PROTOBUF_PREDICT_FALSE(!(x))) goto failure
  while (!ctx->Done(&ptr)) {
    ::PROTOBUF_NAMESPACE_ID::uint32 tag;
    ptr = ::PROTOBUF_NAMESPACE_ID::internal::ReadTag(ptr, &tag);
    CHK_(ptr);
    switch (tag >> 3) {
      // int32 room_count = 1;
      case 1:
        if (PROTOBUF_PREDICT_TRUE(static_cast<::PROTOBUF_NAMESPACE_ID::uint8>(tag) == 8)) {
          room_count_ = ::PROTOBUF_NAMESPACE_ID::internal::ReadVarint64(&ptr);
          CHK_(ptr);
        } else goto handle_unusual;
        continue;
      // int32 min_room_size = 2;
      case 2:
        if (PROTOBUF_PREDICT_TRUE(static_cast<::PROTOBUF_NAMESPACE_ID::uint8>(tag) == 16)) {
          min_room_size_ = ::PROTOBUF_NAMESPACE_ID::internal::ReadVarint64(&ptr);
          CHK_(ptr);
        } else goto handle_unusual;
        continue;
      // int32 max_room_size = 3;
      case 3:
        if (PROTOBUF_PREDICT_TRUE(static_cast<::PROTOBUF_NAMESPACE_ID::uint8>(tag) == 24)) {
          max_room_size_ = ::PROTOBUF_NAMESPACE_ID::internal::ReadVarint64(&ptr);
          CHK_(ptr);
        } else goto handle_unusual;
        continue;
      // int32 map_width = 4;
      case 4:
        if (PROTOBUF_PREDICT_TRUE(static_cast<::PROTOBUF_NAMESPACE_ID::uint8>(tag) == 32)) {
          map_width_ = ::PROTOBUF_NAMESPACE_ID::internal::ReadVarint64(&ptr);
          CHK_(ptr);
        } else goto handle_unusual;
        continue;
      // int32 map_height = 5;
      case 5:
        if (PROTOBUF_PREDICT_TRUE(static_cast<::PROTOBUF_NAMESPACE_ID::uint8>(tag) == 40)) {
          map_height_ = ::PROTOBUF_NAMESPACE_ID::internal::ReadVarint64(&ptr);
          CHK_(ptr);
        } else goto handle_unusual;
        continue;
      // int32 expand_chance = 6;
      case 6:
        if (PROTOBUF_PREDICT_TRUE(static_cast<::PROTOBUF_NAMESPACE_ID::uint8>(tag) == 48)) {
          expand_chance_ = ::PROTOBUF_NAMESPACE_ID::internal::ReadVarint64(&ptr);
          CHK_(ptr);
        } else goto handle_unusual;
        continue;
      default: {
      handle_unusual:
        if ((tag & 7) == 4 || tag == 0) {
          ctx->SetLastTag(tag);
          goto success;
        }
        ptr = UnknownFieldParse(tag,
            _internal_metadata_.mutable_unknown_fields<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>(),
            ptr, ctx);
        CHK_(ptr != nullptr);
        continue;
      }
    }  // switch
  }  // while
success:
  return ptr;
failure:
  ptr = nullptr;
  goto success;
#undef CHK_
}

::PROTOBUF_NAMESPACE_ID::uint8* DungenParams::_InternalSerialize(
    ::PROTOBUF_NAMESPACE_ID::uint8* target, ::PROTOBUF_NAMESPACE_ID::io::EpsCopyOutputStream* stream) const {
  // @@protoc_insertion_point(serialize_to_array_start:game.DungenParams)
  ::PROTOBUF_NAMESPACE_ID::uint32 cached_has_bits = 0;
  (void) cached_has_bits;

  // int32 room_count = 1;
  if (this->room_count() != 0) {
    target = stream->EnsureSpace(target);
    target = ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::WriteInt32ToArray(1, this->_internal_room_count(), target);
  }

  // int32 min_room_size = 2;
  if (this->min_room_size() != 0) {
    target = stream->EnsureSpace(target);
    target = ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::WriteInt32ToArray(2, this->_internal_min_room_size(), target);
  }

  // int32 max_room_size = 3;
  if (this->max_room_size() != 0) {
    target = stream->EnsureSpace(target);
    target = ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::WriteInt32ToArray(3, this->_internal_max_room_size(), target);
  }

  // int32 map_width = 4;
  if (this->map_width() != 0) {
    target = stream->EnsureSpace(target);
    target = ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::WriteInt32ToArray(4, this->_internal_map_width(), target);
  }

  // int32 map_height = 5;
  if (this->map_height() != 0) {
    target = stream->EnsureSpace(target);
    target = ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::WriteInt32ToArray(5, this->_internal_map_height(), target);
  }

  // int32 expand_chance = 6;
  if (this->expand_chance() != 0) {
    target = stream->EnsureSpace(target);
    target = ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::WriteInt32ToArray(6, this->_internal_expand_chance(), target);
  }

  if (PROTOBUF_PREDICT_FALSE(_internal_metadata_.have_unknown_fields())) {
    target = ::PROTOBUF_NAMESPACE_ID::internal::WireFormat::InternalSerializeUnknownFieldsToArray(
        _internal_metadata_.unknown_fields<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>(::PROTOBUF_NAMESPACE_ID::UnknownFieldSet::default_instance), target, stream);
  }
  // @@protoc_insertion_point(serialize_to_array_end:game.DungenParams)
  return target;
}

size_t DungenParams::ByteSizeLong() const {
// @@protoc_insertion_point(message_byte_size_start:game.DungenParams)
  size_t total_size = 0;

  ::PROTOBUF_NAMESPACE_ID::uint32 cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void) cached_has_bits;

  // int32 room_count = 1;
  if (this->room_count() != 0) {
    total_size += 1 +
      ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::Int32Size(
        this->_internal_room_count());
  }

  // int32 min_room_size = 2;
  if (this->min_room_size() != 0) {
    total_size += 1 +
      ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::Int32Size(
        this->_internal_min_room_size());
  }

  // int32 max_room_size = 3;
  if (this->max_room_size() != 0) {
    total_size += 1 +
      ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::Int32Size(
        this->_internal_max_room_size());
  }

  // int32 map_width = 4;
  if (this->map_width() != 0) {
    total_size += 1 +
      ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::Int32Size(
        this->_internal_map_width());
  }

  // int32 map_height = 5;
  if (this->map_height() != 0) {
    total_size += 1 +
      ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::Int32Size(
        this->_internal_map_height());
  }

  // int32 expand_chance = 6;
  if (this->expand_chance() != 0) {
    total_size += 1 +
      ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::Int32Size(
        this->_internal_expand_chance());
  }

  if (PROTOBUF_PREDICT_FALSE(_internal_metadata_.have_unknown_fields())) {
    return ::PROTOBUF_NAMESPACE_ID::internal::ComputeUnknownFieldsSize(
        _internal_metadata_, total_size, &_cached_size_);
  }
  int cached_size = ::PROTOBUF_NAMESPACE_ID::internal::ToCachedSize(total_size);
  SetCachedSize(cached_size);
  return total_size;
}

void DungenParams::MergeFrom(const ::PROTOBUF_NAMESPACE_ID::Message& from) {
// @@protoc_insertion_point(generalized_merge_from_start:game.DungenParams)
  GOOGLE_DCHECK_NE(&from, this);
  const DungenParams* source =
      ::PROTOBUF_NAMESPACE_ID::DynamicCastToGenerated<DungenParams>(
          &from);
  if (source == nullptr) {
  // @@protoc_insertion_point(generalized_merge_from_cast_fail:game.DungenParams)
    ::PROTOBUF_NAMESPACE_ID::internal::ReflectionOps::Merge(from, this);
  } else {
  // @@protoc_insertion_point(generalized_merge_from_cast_success:game.DungenParams)
    MergeFrom(*source);
  }
}

void DungenParams::MergeFrom(const DungenParams& from) {
// @@protoc_insertion_point(class_specific_merge_from_start:game.DungenParams)
  GOOGLE_DCHECK_NE(&from, this);
  _internal_metadata_.MergeFrom<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>(from._internal_metadata_);
  ::PROTOBUF_NAMESPACE_ID::uint32 cached_has_bits = 0;
  (void) cached_has_bits;

  if (from.room_count() != 0) {
    _internal_set_room_count(from._internal_room_count());
  }
  if (from.min_room_size() != 0) {
    _internal_set_min_room_size(from._internal_min_room_size());
  }
  if (from.max_room_size() != 0) {
    _internal_set_max_room_size(from._internal_max_room_size());
  }
  if (from.map_width() != 0) {
    _internal_set_map_width(from._internal_map_width());
  }
  if (from.map_height() != 0) {
    _internal_set_map_height(from._internal_map_height());
  }
  if (from.expand_chance() != 0) {
    _internal_set_expand_chance(from._internal_expand_chance());
  }
}

void DungenParams::CopyFrom(const ::PROTOBUF_NAMESPACE_ID::Message& from) {
// @@protoc_insertion_point(generalized_copy_from_start:game.DungenParams)
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}

void DungenParams::CopyFrom(const DungenParams& from) {
// @@protoc_insertion_point(class_specific_copy_from_start:game.DungenParams)
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}

bool DungenParams::IsInitialized() const {
  return true;
}

void DungenParams::InternalSwap(DungenParams* other) {
  using std::swap;
  _internal_metadata_.Swap<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>(&other->_internal_metadata_);
  ::PROTOBUF_NAMESPACE_ID::internal::memswap<
      PROTOBUF_FIELD_OFFSET(DungenParams, expand_chance_)
      + sizeof(DungenParams::expand_chance_)
      - PROTOBUF_FIELD_OFFSET(DungenParams, room_count_)>(
          reinterpret_cast<char*>(&room_count_),
          reinterpret_cast<char*>(&other->room_count_));
}

::PROTOBUF_NAMESPACE_ID::Metadata DungenParams::GetMetadata() const {
  return GetMetadataStatic();
}


// ===================================================================

class ActionBinds::_Internal {
 public:
};

ActionBinds::ActionBinds(::PROTOBUF_NAMESPACE_ID::Arena* arena)
  : ::PROTOBUF_NAMESPACE_ID::Message(arena),
  action_binds_(arena) {
  SharedCtor();
  RegisterArenaDtor(arena);
  // @@protoc_insertion_point(arena_constructor:game.ActionBinds)
}
ActionBinds::ActionBinds(const ActionBinds& from)
  : ::PROTOBUF_NAMESPACE_ID::Message(),
      action_binds_(from.action_binds_) {
  _internal_metadata_.MergeFrom<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>(from._internal_metadata_);
  // @@protoc_insertion_point(copy_constructor:game.ActionBinds)
}

void ActionBinds::SharedCtor() {
  ::PROTOBUF_NAMESPACE_ID::internal::InitSCC(&scc_info_ActionBinds_proto_2fgame_2eproto.base);
}

ActionBinds::~ActionBinds() {
  // @@protoc_insertion_point(destructor:game.ActionBinds)
  SharedDtor();
  _internal_metadata_.Delete<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>();
}

void ActionBinds::SharedDtor() {
  GOOGLE_DCHECK(GetArena() == nullptr);
}

void ActionBinds::ArenaDtor(void* object) {
  ActionBinds* _this = reinterpret_cast< ActionBinds* >(object);
  (void)_this;
}
void ActionBinds::RegisterArenaDtor(::PROTOBUF_NAMESPACE_ID::Arena*) {
}
void ActionBinds::SetCachedSize(int size) const {
  _cached_size_.Set(size);
}
const ActionBinds& ActionBinds::default_instance() {
  ::PROTOBUF_NAMESPACE_ID::internal::InitSCC(&::scc_info_ActionBinds_proto_2fgame_2eproto.base);
  return *internal_default_instance();
}


void ActionBinds::Clear() {
// @@protoc_insertion_point(message_clear_start:game.ActionBinds)
  ::PROTOBUF_NAMESPACE_ID::uint32 cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void) cached_has_bits;

  action_binds_.Clear();
  _internal_metadata_.Clear<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>();
}

const char* ActionBinds::_InternalParse(const char* ptr, ::PROTOBUF_NAMESPACE_ID::internal::ParseContext* ctx) {
#define CHK_(x) if (PROTOBUF_PREDICT_FALSE(!(x))) goto failure
  while (!ctx->Done(&ptr)) {
    ::PROTOBUF_NAMESPACE_ID::uint32 tag;
    ptr = ::PROTOBUF_NAMESPACE_ID::internal::ReadTag(ptr, &tag);
    CHK_(ptr);
    switch (tag >> 3) {
      // repeated .game.ActionBindEntry action_binds = 1;
      case 1:
        if (PROTOBUF_PREDICT_TRUE(static_cast<::PROTOBUF_NAMESPACE_ID::uint8>(tag) == 10)) {
          ptr -= 1;
          do {
            ptr += 1;
            ptr = ctx->ParseMessage(_internal_add_action_binds(), ptr);
            CHK_(ptr);
            if (!ctx->DataAvailable(ptr)) break;
          } while (::PROTOBUF_NAMESPACE_ID::internal::ExpectTag<10>(ptr));
        } else goto handle_unusual;
        continue;
      default: {
      handle_unusual:
        if ((tag & 7) == 4 || tag == 0) {
          ctx->SetLastTag(tag);
          goto success;
        }
        ptr = UnknownFieldParse(tag,
            _internal_metadata_.mutable_unknown_fields<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>(),
            ptr, ctx);
        CHK_(ptr != nullptr);
        continue;
      }
    }  // switch
  }  // while
success:
  return ptr;
failure:
  ptr = nullptr;
  goto success;
#undef CHK_
}

::PROTOBUF_NAMESPACE_ID::uint8* ActionBinds::_InternalSerialize(
    ::PROTOBUF_NAMESPACE_ID::uint8* target, ::PROTOBUF_NAMESPACE_ID::io::EpsCopyOutputStream* stream) const {
  // @@protoc_insertion_point(serialize_to_array_start:game.ActionBinds)
  ::PROTOBUF_NAMESPACE_ID::uint32 cached_has_bits = 0;
  (void) cached_has_bits;

  // repeated .game.ActionBindEntry action_binds = 1;
  for (unsigned int i = 0,
      n = static_cast<unsigned int>(this->_internal_action_binds_size()); i < n; i++) {
    target = stream->EnsureSpace(target);
    target = ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::
      InternalWriteMessage(1, this->_internal_action_binds(i), target, stream);
  }

  if (PROTOBUF_PREDICT_FALSE(_internal_metadata_.have_unknown_fields())) {
    target = ::PROTOBUF_NAMESPACE_ID::internal::WireFormat::InternalSerializeUnknownFieldsToArray(
        _internal_metadata_.unknown_fields<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>(::PROTOBUF_NAMESPACE_ID::UnknownFieldSet::default_instance), target, stream);
  }
  // @@protoc_insertion_point(serialize_to_array_end:game.ActionBinds)
  return target;
}

size_t ActionBinds::ByteSizeLong() const {
// @@protoc_insertion_point(message_byte_size_start:game.ActionBinds)
  size_t total_size = 0;

  ::PROTOBUF_NAMESPACE_ID::uint32 cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void) cached_has_bits;

  // repeated .game.ActionBindEntry action_binds = 1;
  total_size += 1UL * this->_internal_action_binds_size();
  for (const auto& msg : this->action_binds_) {
    total_size +=
      ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::MessageSize(msg);
  }

  if (PROTOBUF_PREDICT_FALSE(_internal_metadata_.have_unknown_fields())) {
    return ::PROTOBUF_NAMESPACE_ID::internal::ComputeUnknownFieldsSize(
        _internal_metadata_, total_size, &_cached_size_);
  }
  int cached_size = ::PROTOBUF_NAMESPACE_ID::internal::ToCachedSize(total_size);
  SetCachedSize(cached_size);
  return total_size;
}

void ActionBinds::MergeFrom(const ::PROTOBUF_NAMESPACE_ID::Message& from) {
// @@protoc_insertion_point(generalized_merge_from_start:game.ActionBinds)
  GOOGLE_DCHECK_NE(&from, this);
  const ActionBinds* source =
      ::PROTOBUF_NAMESPACE_ID::DynamicCastToGenerated<ActionBinds>(
          &from);
  if (source == nullptr) {
  // @@protoc_insertion_point(generalized_merge_from_cast_fail:game.ActionBinds)
    ::PROTOBUF_NAMESPACE_ID::internal::ReflectionOps::Merge(from, this);
  } else {
  // @@protoc_insertion_point(generalized_merge_from_cast_success:game.ActionBinds)
    MergeFrom(*source);
  }
}

void ActionBinds::MergeFrom(const ActionBinds& from) {
// @@protoc_insertion_point(class_specific_merge_from_start:game.ActionBinds)
  GOOGLE_DCHECK_NE(&from, this);
  _internal_metadata_.MergeFrom<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>(from._internal_metadata_);
  ::PROTOBUF_NAMESPACE_ID::uint32 cached_has_bits = 0;
  (void) cached_has_bits;

  action_binds_.MergeFrom(from.action_binds_);
}

void ActionBinds::CopyFrom(const ::PROTOBUF_NAMESPACE_ID::Message& from) {
// @@protoc_insertion_point(generalized_copy_from_start:game.ActionBinds)
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}

void ActionBinds::CopyFrom(const ActionBinds& from) {
// @@protoc_insertion_point(class_specific_copy_from_start:game.ActionBinds)
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}

bool ActionBinds::IsInitialized() const {
  return true;
}

void ActionBinds::InternalSwap(ActionBinds* other) {
  using std::swap;
  _internal_metadata_.Swap<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>(&other->_internal_metadata_);
  action_binds_.InternalSwap(&other->action_binds_);
}

::PROTOBUF_NAMESPACE_ID::Metadata ActionBinds::GetMetadata() const {
  return GetMetadataStatic();
}


// @@protoc_insertion_point(namespace_scope)
}  // namespace game
PROTOBUF_NAMESPACE_OPEN
template<> PROTOBUF_NOINLINE ::game::ActionBindEntry* Arena::CreateMaybeMessage< ::game::ActionBindEntry >(Arena* arena) {
  return Arena::CreateMessageInternal< ::game::ActionBindEntry >(arena);
}
template<> PROTOBUF_NOINLINE ::game::GameParams* Arena::CreateMaybeMessage< ::game::GameParams >(Arena* arena) {
  return Arena::CreateMessageInternal< ::game::GameParams >(arena);
}
template<> PROTOBUF_NOINLINE ::game::DungenParams* Arena::CreateMaybeMessage< ::game::DungenParams >(Arena* arena) {
  return Arena::CreateMessageInternal< ::game::DungenParams >(arena);
}
template<> PROTOBUF_NOINLINE ::game::ActionBinds* Arena::CreateMaybeMessage< ::game::ActionBinds >(Arena* arena) {
  return Arena::CreateMessageInternal< ::game::ActionBinds >(arena);
}
PROTOBUF_NAMESPACE_CLOSE

// @@protoc_insertion_point(global_scope)
#include <google/protobuf/port_undef.inc>
